# Generated by Django 5.1.4 on 2026-01-14 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Module code (M1, M2, ..., M15)', max_length=10, unique=True)),
                ('unesco_aspect', models.CharField(choices=[('human_centered', 'Human-Centred Mindset'), ('ethics', 'Ethics'), ('ai_foundations', 'AI Foundations'), ('ai_pedagogy', 'AI Pedagogy'), ('professional_development', 'Professional Development')], help_text='UNESCO AI CFT Aspect (1-5)', max_length=50)),
                ('proficiency_level', models.CharField(choices=[('Acquire', 'Acquire'), ('Deepen', 'Deepen'), ('Create', 'Create')], help_text='UNESCO Proficiency Level', max_length=20)),
                ('title', models.CharField(help_text='Module title (English)', max_length=200)),
                ('description', models.TextField(help_text='Brief description (2-3 sentences)')),
                ('order_index', models.IntegerField(help_text='Display order (1-15)', unique=True)),
                ('estimated_hours', models.IntegerField(default=4, help_text='Estimated completion time in hours')),
                ('hero_image_url', models.CharField(blank=True, help_text='Hero image URL or static path', max_length=500)),
                ('learning_objectives', models.JSONField(default=list, help_text='Array of learning objectives (4-6 items)')),
                ('module_overview', models.TextField(blank=True, help_text='Module overview text for Tab 1 (100-200 words)')),
                ('prerequisites', models.JSONField(default=list, help_text='Array of required module IDs: [1, 2, 3]')),
                ('is_published', models.BooleanField(default=False, help_text='Module visible to users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ModuleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('main_content', 'Κύριο Περιεχόμενο'), ('activity', 'Δραστηριότητα'), ('assessment', 'Αξιολόγηση'), ('reflection', 'Αναστοχασμός')], help_text='Content tab type', max_length=50)),
                ('subject_area', models.CharField(choices=[('Universal', 'Universal (All Subjects)'), ('Mathematics', 'Μαθηματικά'), ('Science', 'Φυσικές Επιστήμες'), ('Physics', 'Φυσική'), ('Chemistry', 'Χημεία'), ('Biology', 'Βιολογία'), ('Greek Language', 'Ελληνική Γλώσσα'), ('English Language', 'Αγγλική Γλώσσα'), ('History', 'Ιστορία'), ('Geography', 'Γεωγραφία'), ('Religious Studies', 'Θρησκευτικά'), ('Physical Education', 'Φυσική Αγωγή'), ('Art', 'Καλλιτεχνικά'), ('Music', 'Μουσική'), ('Technology', 'Τεχνολογία'), ('Computer Science', 'Πληροφορική')], default='Universal', max_length=50)),
                ('grade_level', models.CharField(choices=[('All', 'All Grades'), ('Primary', 'Δημοτικό'), ('Secondary', 'Γυμνάσιο'), ('High School', 'Λύκειο'), ('Mixed', 'Μικτό')], default='All', max_length=50)),
                ('content_data', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='modules.module')),
            ],
            options={
                'verbose_name': 'Module Content',
                'verbose_name_plural': 'Module Contents',
                'ordering': ['module__order_index', 'content_type'],
                'unique_together': {('module', 'content_type', 'subject_area', 'grade_level')},
            },
        ),
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='not_started', max_length=20)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('introduction_completed', models.BooleanField(default=False)),
                ('introduction_completed_at', models.DateTimeField(blank=True, null=True)),
                ('main_content_completed', models.BooleanField(default=False)),
                ('main_content_completed_at', models.DateTimeField(blank=True, null=True)),
                ('activity_completed', models.BooleanField(default=False)),
                ('activity_completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_completed', models.BooleanField(default=False)),
                ('assessment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('reflection_completed', models.BooleanField(default=False)),
                ('reflection_completed_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='modules.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Module Progress',
                'verbose_name_plural': 'User Module Progress',
                'ordering': ['-last_accessed_at'],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
