# Generated by Django 6.0.1 on 2026-02-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoduleprogress',
            name='reflection_rag_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='reflection_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
