# Generated by Django 6.0.1 on 2026-02-11 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_usermoduleprogress_reflection_rag_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecontent',
            name='grade_level',
            field=models.CharField(choices=[('kindergarten', 'Kindergarten / Pre-K'), ('primary', 'Primary / Elementary (1-6)'), ('lower_secondary', 'Lower Secondary / Middle School (7-9)'), ('upper_secondary', 'Upper Secondary / High School (10-12)'), ('university', 'University / Higher Education')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='modulecontent',
            name='subject_area',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('language_arts', 'Language Arts / English'), ('science', 'Science (General)'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('social_studies', 'Social Studies'), ('history', 'History'), ('geography', 'Geography'), ('foreign_languages', 'World Languages'), ('computer_science', 'Computer Science / ICT'), ('physical_education', 'Physical Education & Health'), ('arts', 'Arts'), ('special_education', 'Special Education'), ('early_childhood', 'Early Childhood Education'), ('other', 'Other')], default='Universal', max_length=50),
        ),
        migrations.CreateModel(
            name='Tab3PromptLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Greek Language', 'Greek Language'), ('Science', 'Science'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Computer Science', 'Computer Science'), ('History', 'History'), ('Geography', 'Geography'), ('Foreign Languages', 'Foreign Languages'), ('Physical Education', 'Physical Education'), ('Arts & Music', 'Arts & Music'), ('Special Education', 'Special Education'), ('Early Childhood', 'Early Childhood'), ('Other', 'Other/General')], max_length=50)),
                ('grade_level', models.CharField(blank=True, max_length=20, null=True)),
                ('prompt_type', models.CharField(choices=[('good', 'Good Prompt (Challenge 1)'), ('bad', 'Bad Prompt (Challenge 2)'), ('lesson_plan', 'Lesson Plan Generator'), ('quiz', 'Quiz/Assessment Creator'), ('differentiation', 'Differentiation Helper')], max_length=50)),
                ('prompt_template', models.TextField(help_text='Use {{topic}} and {{grade}} as placeholders')),
                ('example_topic', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TAB 3 Prompt',
                'verbose_name_plural': 'TAB 3 Prompt Library',
                'db_table': 'tab3_prompt_library',
                'indexes': [models.Index(fields=['subject', 'prompt_type'], name='tab3_prompt_subject_9339f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tab3UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.IntegerField(default=1)),
                ('challenge1_completed', models.BooleanField(default=False)),
                ('challenge1_tool', models.CharField(blank=True, choices=[('ChatGPT', 'ChatGPT'), ('Claude', 'Claude'), ('Gemini', 'Gemini'), ('Copilot', 'Microsoft Copilot'), ('Perplexity', 'Perplexity'), ('DeepSeek', 'DeepSeek'), ('Other', 'Other')], max_length=50)),
                ('challenge1_rating', models.IntegerField(blank=True, null=True)),
                ('challenge1_tags', models.JSONField(blank=True, default=list)),
                ('challenge1_note', models.TextField(blank=True)),
                ('challenge1_completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge2_completed', models.BooleanField(default=False)),
                ('challenge2_observations', models.JSONField(blank=True, default=list)),
                ('challenge2_comparison', models.TextField(blank=True)),
                ('challenge2_completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge3_completed', models.BooleanField(default=False)),
                ('challenge3_prompt_choice', models.CharField(blank=True, max_length=50)),
                ('challenge3_custom_topic', models.CharField(blank=True, max_length=200)),
                ('challenge3_custom_grade', models.CharField(blank=True, max_length=50)),
                ('challenge3_tool', models.CharField(blank=True, choices=[('ChatGPT', 'ChatGPT'), ('Claude', 'Claude'), ('Gemini', 'Gemini'), ('Copilot', 'Microsoft Copilot'), ('Perplexity', 'Perplexity'), ('DeepSeek', 'DeepSeek'), ('Other', 'Other')], max_length=50)),
                ('challenge3_rating', models.IntegerField(blank=True, null=True)),
                ('challenge3_will_use', models.CharField(blank=True, choices=[('as_is', 'Yes, as-is'), ('minor_edits', 'Yes, with minor edits'), ('needs_work', 'Maybe, needs work'), ('not_useful', 'No, not useful')], max_length=50)),
                ('challenge3_result', models.TextField(blank=True)),
                ('challenge3_completed_at', models.DateTimeField(blank=True, null=True)),
                ('reflection_completed', models.BooleanField(default=False)),
                ('reflection_best_tool', models.TextField(blank=True)),
                ('reflection_surprise', models.TextField(blank=True)),
                ('reflection_completed_at', models.DateTimeField(blank=True, null=True)),
                ('activity_completed', models.BooleanField(default=False)),
                ('activity_completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TAB 3 User Activity',
                'verbose_name_plural': 'TAB 3 User Activities',
                'db_table': 'tab3_user_activity',
                'indexes': [models.Index(fields=['user'], name='tab3_user_a_user_id_c826be_idx'), models.Index(fields=['activity_completed'], name='tab3_user_a_activit_4c2b3b_idx')],
                'unique_together': {('user', 'module_id')},
            },
        ),
        migrations.CreateModel(
            name='Tab3UserToolkit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('ai_result', models.TextField(blank=True)),
                ('tool_used', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('grade_level', models.CharField(blank=True, max_length=50)),
                ('prompt_type', models.CharField(blank=True, max_length=50)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TAB 3 Toolkit Item',
                'verbose_name_plural': 'TAB 3 Toolkit Items',
                'db_table': 'tab3_user_toolkit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='tab3_user_t_user_id_bcbf58_idx')],
            },
        ),
    ]
