# Generated by Django 6.0.1 on 2026-02-23 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_assessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReflectionTension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tension_label', models.CharField(help_text='Short label (max 6 words) identifying the tension', max_length=100)),
                ('left_pole', models.TextField(help_text="Left pole description grounded in teacher's wording")),
                ('right_pole', models.TextField(help_text="Right pole description grounded in teacher's wording")),
                ('grounding_quote', models.TextField(help_text='Verbatim quote from reflection supporting this tension (audit trail)')),
                ('selected_position', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='User self-positioning: 1=strongly left pole, 5=strongly right pole')),
                ('optional_comment', models.CharField(blank=True, help_text="User's optional explanation for their positioning (max 150 chars)", max_length=150, null=True)),
                ('time_spent_ms', models.IntegerField(blank=True, help_text='Milliseconds user spent interacting with RTM card', null=True)),
                ('comment_used', models.BooleanField(default=False, help_text='Whether user added an optional comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_tensions', to='modules.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_tensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reflection Tension',
                'verbose_name_plural': 'Reflection Tensions',
                'db_table': 'reflection_tensions',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user'], name='reflection__user_id_6faa5f_idx'), models.Index(fields=['module'], name='reflection__module__0a9eaa_idx'), models.Index(fields=['tension_label'], name='reflection__tension_57ce37_idx'), models.Index(fields=['selected_position'], name='reflection__selecte_e8c7e5_idx'), models.Index(fields=['created_at'], name='reflection__created_3b6ac1_idx')],
                'unique_together': {('user', 'module', 'tension_label')},
            },
        ),
    ]
