# Generated by Django 6.0.1 on 2026-02-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_reflectiontension'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoduleprogress',
            name='reflection_peer_synthesis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
