# Generated by Django 6.0.1 on 2026-03-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_usermoduleprogress_reflection_peer_synthesis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tab3useractivity',
            name='challenge1_note',
        ),
        migrations.RemoveField(
            model_name='tab3useractivity',
            name='challenge1_rating',
        ),
        migrations.RemoveField(
            model_name='tab3useractivity',
            name='challenge1_tags',
        ),
        migrations.RemoveField(
            model_name='tab3useractivity',
            name='challenge1_tool',
        ),
        migrations.RemoveField(
            model_name='tab3useractivity',
            name='challenge2_comparison',
        ),
        migrations.RemoveField(
            model_name='tab3useractivity',
            name='challenge2_observations',
        ),
        migrations.RemoveField(
            model_name='tab3useractivity',
            name='challenge3_custom_grade',
        ),
        migrations.RemoveField(
            model_name='tab3useractivity',
            name='challenge3_custom_topic',
        ),
        migrations.RemoveField(
            model_name='tab3useractivity',
            name='challenge3_prompt_choice',
        ),
        migrations.RemoveField(
            model_name='tab3useractivity',
            name='challenge3_rating',
        ),
        migrations.RemoveField(
            model_name='tab3useractivity',
            name='challenge3_result',
        ),
        migrations.RemoveField(
            model_name='tab3useractivity',
            name='challenge3_tool',
        ),
        migrations.RemoveField(
            model_name='tab3useractivity',
            name='challenge3_will_use',
        ),
        migrations.RemoveField(
            model_name='tab3useractivity',
            name='reflection_best_tool',
        ),
        migrations.RemoveField(
            model_name='tab3useractivity',
            name='reflection_surprise',
        ),
        migrations.AddField(
            model_name='tab3useractivity',
            name='challenge_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
