# Generated by Django 6.0.1 on 2026-03-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_remove_tab3useractivity_challenge1_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoduleprogress',
            name='reflection_dtp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
