# Generated by Django 6.0.1 on 2026-04-18 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_usermoduleprogress_reflection_dtp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIOutputDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('rag', 'RAG Feedback'), ('rtm', 'Reflective Tension Mapper'), ('dtp', 'Developmental Trajectory Predictor')], max_length=10)),
                ('rating', models.CharField(choices=[('yes', 'Relevant'), ('no', 'Not relevant'), ('partial', 'Partially relevant')], max_length=10)),
                ('reason', models.CharField(blank=True, choices=[('mismatch', 'Does not match my subject context'), ('misinterpretation', 'AI misunderstood my reflection'), ('generic', 'Too generic / low value'), ('pedagogical', 'Pedagogical disagreement'), ('other', 'Other')], max_length=20, null=True)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_disputes', to='modules.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feature_type', 'rating'], name='modules_aio_feature_c6c75f_idx'), models.Index(fields=['module', 'feature_type'], name='modules_aio_module__cfe64a_idx'), models.Index(fields=['user', 'module'], name='modules_aio_user_id_f77d7e_idx')],
                'unique_together': {('user', 'module', 'feature_type')},
            },
        ),
    ]
