# Generated by Django 6.0.1 on 2026-04-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_aioutputdispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflectiontension',
            name='position_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
