# Generated by Django 6.0.1 on 2026-05-02 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_reflectiontension_position_confirmed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecontent',
            name='subject_area',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('language_arts', 'Language Arts / English'), ('science', 'Science (General)'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('social_studies', 'Social Studies'), ('history', 'History'), ('geography', 'Geography'), ('foreign_languages', 'World Languages'), ('computer_science', 'Computer Science / ICT'), ('physical_education', 'Physical Education & Health'), ('arts', 'Arts'), ('special_education', 'Special Education'), ('early_childhood', 'Early Childhood Education'), ('other', 'Primary Teacher / General Education')], default='Universal', max_length=50),
        ),
        migrations.AlterField(
            model_name='tab3promptlibrary',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Greek Language', 'Greek Language'), ('Science', 'Science'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Computer Science', 'Computer Science'), ('History', 'History'), ('Geography', 'Geography'), ('Foreign Languages', 'Foreign Languages'), ('Physical Education', 'Physical Education'), ('Arts & Music', 'Arts & Music'), ('Special Education', 'Special Education'), ('Early Childhood', 'Early Childhood'), ('Other', 'Primary Teacher / General Education')], max_length=50),
        ),
        migrations.CreateModel(
            name='Tab3RepositorySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.IntegerField(default=2)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('subject_area', models.CharField(max_length=50)),
                ('grade_level', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('canvas_data', models.JSONField(blank=True, default=dict)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Peer Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='pending', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TAB3 Repository Submission',
                'verbose_name_plural': 'TAB3 Repository Submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['review_status', '-submitted_at'], name='modules_tab_review__b23502_idx'), models.Index(fields=['module', 'review_status'], name='modules_tab_module__e410c3_idx')],
            },
        ),
    ]
