# Generated by Django 6.0.1 on 2026-05-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_alter_modulecontent_subject_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab3repositorysubmission',
            name='review_status',
            field=models.CharField(choices=[('community_shared', 'Community Shared (Practice Workshop)'), ('pending', 'Pending Peer Review (legacy)'), ('approved', 'Approved (legacy)'), ('rejected', 'Rejected (legacy)'), ('needs_revision', 'Needs Revision (legacy)')], default='pending', max_length=20),
        ),
    ]
