# Generated by Django 6.0.1 on 2026-05-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_add_community_shared_to_repository_submission_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoduleprogress',
            name='reflection_dtp_xai',
            field=models.TextField(blank=True, null=True),
        ),
    ]
