# Generated by Django 6.0.1 on 2026-05-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_usermoduleprogress_reflection_dtp_xai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aioutputdispute',
            name='feature_type',
            field=models.CharField(choices=[('rag', 'RAG Feedback'), ('rtm', 'Reflective Tension Mapper'), ('dtp', 'Developmental Trajectory Predictor'), ('peer', 'Peer Synthesis')], max_length=10),
        ),
    ]
