# Generated by Django 6.0.1 on 2026-05-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0014_alter_aioutputdispute_feature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoduleprogress',
            name='reflection_input_modality',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('voice', 'Voice'), ('mixed', 'Mixed')], max_length=10, null=True),
        ),
    ]
