# Generated by Django 6.0.1 on 2026-05-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0015_usermoduleprogress_reflection_input_modality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='estimated_hours',
            field=models.IntegerField(default=5, help_text="Estimated time-on-task per module in hours. Phase H TD-028 (2026-05-27) standardised this to 5 hours uniformly across all 15 modules, anchored to the §4 decomposition in PROODOS_PROGRAMME_DURATION_METHODOLOGY_v1.2: 20m TAB1 + 6m video overview + 75m TAB2 reading + 120m TAB3 practice + 12m Community Forum + 30m TAB4 quiz + 45m TAB5 reflection = 308min ≈ 5h 8m standard module; +25min Practice Workshop for M9/M13/M14 only. Programme-wide average across all 15 modules: ~5h 13m. The 5h-uniform value is conservative relative to that measured aggregate. Module sum (15×5=75h) matches the certificate's CERTIFICATE_PROGRAMME_HOURS exactly."),
        ),
    ]
