# Generated by Django 6.0.1 on 2026-05-03 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0011_alter_modulecontent_subject_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artefact_type', models.CharField(help_text="Artefact type identifier: 'm13_workflow', 'm9_lesson', 'm14_gamified_unit'.", max_length=50)),
                ('artefact_id', models.IntegerField(help_text='ID of the artefact in its source table (Tab3RepositorySubmission, Tab3UserActivity, etc.).')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='The artefact summary or description shown to peers.')),
                ('author_pseudonym', models.CharField(max_length=50)),
                ('subject_area', models.CharField(db_index=True, max_length=50)),
                ('grade_level', models.CharField(max_length=20)),
                ('thumbs_up_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False, help_text="Researcher reactive moderation flag. Hidden posts don't appear in feeds.")),
                ('hidden_reason', models.CharField(blank=True, choices=[('safety_violation', 'Platform safety violation'), ('off_topic_spam', 'Off-topic / spam'), ('contains_pii', 'Contains real student PII'), ('copyright_violation', 'Copyright violation')], help_text='If hidden, the policy category triggering the action.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author_pseudonym', models.CharField(max_length=50)),
                ('subject_area', models.CharField(max_length=50)),
                ('thumbs_up_count', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='peer_blog.blogpost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogThumbsUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peer_blog.blogcomment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peer_blog.blogpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['module', 'subject_area', '-created_at'], name='blog_module_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['module', '-thumbs_up_count'], name='blog_module_thumbs_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['artefact_type', 'artefact_id'], name='blog_artefact_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['post', 'created_at'], name='peer_blog_b_post_id_9619f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='blogthumbsup',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('user', 'post'), name='unique_user_post_thumbs_up'),
        ),
        migrations.AddConstraint(
            model_name='blogthumbsup',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('user', 'comment'), name='unique_user_comment_thumbs_up'),
        ),
        migrations.AddConstraint(
            model_name='blogthumbsup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('post__isnull', False)), models.Q(('comment__isnull', False), ('post__isnull', True)), _connector='OR'), name='thumbs_up_post_xor_comment'),
        ),
    ]
