# Generated by Django 6.0.1 on 2026-05-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='hidden_reason',
            field=models.CharField(blank=True, choices=[('safety_violation', 'Platform safety violation'), ('off_topic_spam', 'Off-topic / spam'), ('contains_pii', 'Contains real student PII'), ('copyright_violation', 'Copyright violation'), ('author_deleted', 'Deleted by author')], help_text='If hidden, the policy category or author action triggering the action.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='hidden_reason',
            field=models.CharField(blank=True, choices=[('safety_violation', 'Platform safety violation'), ('off_topic_spam', 'Off-topic / spam'), ('contains_pii', 'Contains real student PII'), ('copyright_violation', 'Copyright violation'), ('author_withdrawn', 'Withdrawn by author')], help_text='If hidden, the policy category or author action triggering the action.', max_length=100, null=True),
        ),
    ]
