# Generated by Django 6.0.1 on 2026-05-25 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateOfAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True, help_text='Set on first issuance; never changes on re-render.')),
                ('verification_code', models.CharField(help_text='16-char URL-safe random code used in the public /certification/verify/<code>/ endpoint. Generated via generate_verification_code() helper with retry-on-collision.', max_length=16, unique=True)),
                ('teacher_display', models.CharField(help_text='Frozen at issuance. Built from user.get_full_name() or user.username; survives later profile renames.', max_length=255)),
                ('modules_summary', models.JSONField(help_text='Frozen list of the 15 modules at issuance, each entry {"code": "M1", "title": "...", "aspect": "Human-Centred Mindset", "level": "Acquire"}. Survives later edits to Module rows.')),
                ('instrument_version_t2', models.CharField(help_text="AilstResponse.instrument_version of the T2 row that triggered issuance (typically 'ning_2025_v1').", max_length=20)),
                ('pdf_metadata_version', models.CharField(default='v1', help_text='Bumped on PDF template revisions (e.g. when the Greek translation lands per Phase H Path A) without requiring a new row. The Article 50(2) JSON-LD body block reflects this version.', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_of_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate of Attendance',
                'verbose_name_plural': 'Certificates of Attendance',
                'db_table': 'certification_certificate_of_attendance',
                'ordering': ['-issued_at'],
            },
        ),
    ]
