# Generated by Django 6.0.1 on 2026-05-10 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0002_drop_dead_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('platform_use', 'Platform terms of use'), ('research_participation', 'Research participation'), ('data_sharing', 'Data sharing with affiliated researchers'), ('video_recording', 'Video recording (interviews/focus groups)'), ('ai_disclosure', 'EU AI Act Article 50 disclosure acknowledgment')], max_length=30)),
                ('granted', models.BooleanField(default=True)),
                ('consent_text', models.TextField(help_text="Verbatim copy of the text the user agreed to at consent time. Never re-edited. Source of truth for IRB / legal defensibility ('what exactly did the user agree to on this date?').")),
                ('version', models.CharField(help_text="Version label of the consent text, e.g., 'v1', 'v2_irb_revised'.", max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Redacted (set NULL) after 30 days per GDPR data minimization. See manage.py redact_old_consent_ips.', null=True)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the consent was granted. Default is NOW; explicit override allowed for backfill migrations (e.g., legacy boolean migration).')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Set if user revokes this consent (e.g., via Privacy dashboard). Row preserved; granted_at..revoked_at delimits active period.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consent Record',
                'verbose_name_plural': 'Consent Records',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['user', 'consent_type', '-granted_at'], name='idx_consent_user_type_time'), models.Index(fields=['consent_type', 'granted'], name='idx_consent_type_granted')],
                'constraints': [models.CheckConstraint(condition=models.Q(('consent_type__in', ['platform_use', 'research_participation', 'data_sharing', 'video_recording', 'ai_disclosure'])), name='valid_consent_type')],
            },
        ),
    ]
