# Generated by Django 6.0.1 on 2026-05-12 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_migrate_teacherprofile_consents'),
        ('modules', '0012_add_community_shared_to_repository_submission_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIArtefactProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artefact_kind', models.CharField(choices=[('rtm_position', 'RTM tension position'), ('dtp_narrative', 'DTP developmental trajectory narrative'), ('rag_feedback', 'RAG reflection feedback'), ('peer_synthesis', 'Peer reflection synthesis'), ('rag_query', 'Raw rag_queries telemetry row'), ('epilogue_portrait', 'Epilogue Learning Portrait (forward-compat)')], max_length=24)),
                ('artefact_pk', models.CharField(help_text='Primary key in the source table for this artefact_kind, stored as string. Not a Django FK because rag_queries is raw-SQL; integrity is enforced at write time. CharField (not int) because the five source tables use heterogeneous pk types: ReflectionTension uses UUIDField, UserModuleProgress and rag_queries use BigAutoField. The helper coerces to str.', max_length=64)),
                ('model_name', models.CharField(help_text="AI model identifier, e.g., 'gemini-2.5-flash'.", max_length=64)),
                ('generated_at', models.DateTimeField(help_text="When the artefact was generated. For backfill, the source row's created_at.")),
                ('prompt_hash', models.CharField(blank=True, help_text='sha256 of the prompt text + retrieval context (privacy-respecting). Nullable for retroactive backfill where the prompt is not reconstructible.', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(blank=True, help_text='Nullable: rag_queries rows may carry a NULL module_id.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_artefact_provenance', to='modules.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_artefact_provenance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Artefact Provenance',
                'verbose_name_plural': 'AI Artefact Provenance',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', 'artefact_kind'], name='idx_ai_prov_user_kind'), models.Index(fields=['module', 'artefact_kind'], name='idx_ai_prov_module_kind')],
                'constraints': [models.UniqueConstraint(fields=('artefact_kind', 'artefact_pk'), name='uq_ai_provenance_kind_pk')],
            },
        ),
    ]
