# Generated by Django 6.0.1 on 2026-05-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_aiartefactprovenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiartefactprovenance',
            name='artefact_kind',
            field=models.CharField(choices=[('rtm_position', 'RTM tension position'), ('dtp_narrative', 'DTP developmental trajectory narrative'), ('xai_narrative', 'DTP XAI explanation narrative'), ('rag_feedback', 'RAG reflection feedback'), ('peer_synthesis', 'Peer reflection synthesis'), ('rag_query', 'Raw rag_queries telemetry row'), ('epilogue_portrait', 'Epilogue Learning Portrait (forward-compat)')], max_length=24),
        ),
    ]
