# Generated by Django 6.0.1 on 2026-05-25 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_add_followup_recruitment_consent_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consentrecord',
            name='valid_consent_type',
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='consent_type',
            field=models.CharField(choices=[('platform_use', 'Platform terms of use'), ('research_participation', 'Research participation'), ('data_sharing', 'Data sharing with affiliated researchers'), ('video_recording', 'Video recording (interviews/focus groups)'), ('ai_disclosure', 'EU AI Act Article 50 disclosure acknowledgment')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='consentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('consent_type__in', ['platform_use', 'research_participation', 'data_sharing', 'video_recording', 'ai_disclosure'])), name='valid_consent_type'),
        ),
    ]
