# Generated by Django 6.0.1 on 2026-01-08 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_area', models.CharField(blank=True, choices=[('mathematics', 'Μαθηματικά'), ('greek_language', 'Ελληνική Γλώσσα'), ('science_general', 'Φυσικές Επιστήμες (Γενικά)'), ('physics', 'Φυσική'), ('chemistry', 'Χημεία'), ('biology', 'Βιολογία'), ('computer_science', 'Πληροφορική'), ('history', 'Ιστορία'), ('geography', 'Γεωγραφία'), ('foreign_languages', 'Ξένες Γλώσσες'), ('physical_education', 'Φυσική Αγωγή'), ('arts_music', 'Καλλιτεχνικά & Μουσική'), ('special_education', 'Ειδική Αγωγή'), ('early_childhood', 'Προσχολική Εκπαίδευση'), ('other', 'Άλλο')], help_text='Το κύριο μάθημα που διδάσκετε', max_length=50, null=True, verbose_name='Γνωστικό Αντικείμενο')),
                ('subject_area_other', models.CharField(blank=True, help_text="Αν επιλέξατε 'Άλλο', προσδιορίστε εδώ", max_length=100, verbose_name='Άλλο Αντικείμενο')),
                ('grade_level', models.CharField(blank=True, choices=[('kindergarten', 'Νηπιαγωγείο'), ('primary', 'Δημοτικό (1-6)'), ('lower_secondary', 'Γυμνάσιο (7-9)'), ('upper_secondary', 'Λύκειο (10-12)'), ('university', 'Πανεπιστήμιο/ΤΕΙ')], help_text='Σε ποια βαθμίδα διδάσκετε κυρίως;', max_length=20, null=True, verbose_name='Βαθμίδα Εκπαίδευσης')),
                ('teaching_years', models.CharField(blank=True, choices=[('0-5', '0-5 χρόνια'), ('6-15', '6-15 χρόνια'), ('16-25', '16-25 χρόνια'), ('25+', '25+ χρόνια')], max_length=10, null=True, verbose_name='Χρόνια Διδακτικής Εμπειρίας')),
                ('school_location', models.CharField(blank=True, choices=[('urban', 'Αστική Περιοχή'), ('suburban', 'Προαστιακή Περιοχή'), ('rural', 'Αγροτική/Απομακρυσμένη Περιοχή')], max_length=20, null=True, verbose_name='Τοποθεσία Σχολείου')),
                ('average_class_size', models.CharField(blank=True, choices=[('small', 'Μικρή (<15 μαθητές)'), ('medium', 'Μεσαία (15-25 μαθητές)'), ('large', 'Μεγάλη (26-35 μαθητές)'), ('very_large', 'Πολύ Μεγάλη (>35 μαθητές)')], max_length=20, null=True, verbose_name='Μέσο Μέγεθος Τάξης')),
                ('ai_experience', models.CharField(choices=[('none', 'Καμία - Πρώτη φορά με ΤΝ'), ('basic', 'Βασική - Έχω δοκιμάσει ChatGPT/AI εργαλεία'), ('intermediate', 'Μέτρια - Χρησιμοποιώ AI τακτικά'), ('advanced', 'Προχωρημένη - Ενσωματώνω AI στη διδασκαλία')], default='none', max_length=20, verbose_name='Εμπειρία με Τεχνητή Νοημοσύνη')),
                ('ai_tools_used', models.JSONField(blank=True, default=list, help_text="List of AI tools (e.g., ['ChatGPT', 'Gemini'])", verbose_name='Εργαλεία ΤΝ που έχετε χρησιμοποιήσει')),
                ('ai_teaching_integration', models.TextField(blank=True, help_text='Σύντομη περιγραφή - 100-200 λέξεις', verbose_name='Πώς χρησιμοποιείτε ΤΝ στη διδασκαλία;')),
                ('primary_goals', models.JSONField(blank=True, default=list, help_text='Top 3 goals', verbose_name='Κύριοι Στόχοι Μάθησης')),
                ('preferred_communication_style', models.CharField(choices=[('concise', 'Συνοπτικό - Κύρια σημεία μόνο'), ('detailed', 'Λεπτομερές - Εκτενείς εξηγήσεις'), ('balanced', 'Ισορροπημένο - Συνδυασμός')], default='balanced', max_length=20, verbose_name='Προτιμώμενο Στυλ Επικοινωνίας')),
                ('profile_completed', models.BooleanField(default=False, verbose_name='Προφίλ Ολοκληρωμένο')),
                ('profile_completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Ολοκλήρωσης Προφίλ')),
                ('profile_skipped', models.BooleanField(default=False, verbose_name='Ο χρήστης παρέλειψε το onboarding')),
                ('last_profile_update', models.DateTimeField(auto_now=True, verbose_name='Τελευταία Ενημέρωση')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_consent', models.BooleanField(default=True, verbose_name='Συναίνεση για Χρήση Δεδομένων σε Έρευνα')),
                ('contact_for_research', models.BooleanField(default=False, verbose_name='Δέχομαι επικοινωνία για συνεντεύξεις έρευνας')),
                ('consent_data_sharing', models.BooleanField(default=False, verbose_name='Συναίνεση για διαμοιρασμό δεδομένων')),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Χρόνος Συναίνεσης')),
                ('age_range', models.CharField(blank=True, max_length=20, verbose_name='Ηλικιακό Εύρος')),
                ('gender', models.CharField(blank=True, max_length=50, verbose_name='Φύλο')),
                ('language_primary', models.CharField(blank=True, default='el', max_length=50, verbose_name='Κύρια Γλώσσα')),
                ('notes', models.TextField(blank=True, help_text='Admin notes - internal use only', verbose_name='Σημειώσεις')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
                'db_table': 'teacher_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
