# Generated by Django 6.0.1 on 2026-01-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='age_range',
            field=models.CharField(blank=True, max_length=20, verbose_name='Age Range'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='ai_experience',
            field=models.CharField(choices=[('none', 'None - First time with AI'), ('basic', 'Basic - Have tried ChatGPT/AI tools'), ('intermediate', 'Intermediate - Use AI regularly'), ('advanced', 'Advanced - Integrate AI in teaching')], default='none', max_length=20, verbose_name='AI Experience Level'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='ai_teaching_integration',
            field=models.TextField(blank=True, help_text='Brief description - 100-200 words', verbose_name='How do you use AI in teaching?'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='ai_tools_used',
            field=models.JSONField(blank=True, default=list, help_text="List of AI tools (e.g., ['ChatGPT', 'Gemini', 'Claude'])", verbose_name='AI Tools Used'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='average_class_size',
            field=models.CharField(blank=True, choices=[('small', 'Small (<15 students)'), ('medium', 'Medium (15-25 students)'), ('large', 'Large (26-35 students)'), ('very_large', 'Very Large (>35 students)')], max_length=20, null=True, verbose_name='Average Class Size'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='consent_data_sharing',
            field=models.BooleanField(default=False, verbose_name='Consent to data sharing'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consent Timestamp'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='contact_for_research',
            field=models.BooleanField(default=False, verbose_name='Available for research interviews'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=50, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('kindergarten', 'Kindergarten / Pre-K'), ('primary', 'Primary / Elementary (1-6)'), ('lower_secondary', 'Lower Secondary / Middle School (7-9)'), ('upper_secondary', 'Upper Secondary / High School (10-12)'), ('university', 'University / Higher Education')], help_text='Which grade level do you primarily teach?', max_length=20, null=True, verbose_name='Grade Level'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='language_primary',
            field=models.CharField(blank=True, default='en', max_length=50, verbose_name='Primary Language'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='last_profile_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin notes - internal use only', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='preferred_communication_style',
            field=models.CharField(choices=[('concise', 'Concise - Key points only'), ('detailed', 'Detailed - Extended explanations'), ('balanced', 'Balanced - Mix of both')], default='balanced', max_length=20, verbose_name='Preferred Communication Style'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='primary_goals',
            field=models.JSONField(blank=True, default=list, help_text='Top 3 goals', verbose_name='Primary Learning Goals'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_completed',
            field=models.BooleanField(default=False, verbose_name='Profile Completed'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Profile Completion Date'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_skipped',
            field=models.BooleanField(default=False, verbose_name='User skipped onboarding'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='research_consent',
            field=models.BooleanField(default=True, verbose_name='Consent to use data for research'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='school_location',
            field=models.CharField(blank=True, choices=[('urban', 'Urban Area'), ('suburban', 'Suburban Area'), ('rural', 'Rural / Remote Area')], max_length=20, null=True, verbose_name='School Location'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject_area',
            field=models.CharField(blank=True, choices=[('mathematics', 'Mathematics'), ('language_arts', 'Language Arts / English'), ('science', 'Science (General)'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('social_studies', 'Social Studies'), ('history', 'History'), ('geography', 'Geography'), ('foreign_languages', 'World Languages'), ('computer_science', 'Computer Science / ICT'), ('physical_education', 'Physical Education & Health'), ('arts', 'Arts'), ('special_education', 'Special Education'), ('early_childhood', 'Early Childhood Education'), ('other', 'Other')], help_text='Your primary teaching subject', max_length=50, null=True, verbose_name='Subject Area'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject_area_other',
            field=models.CharField(blank=True, help_text="If you selected 'Other', please specify", max_length=100, verbose_name='Other Subject'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='teaching_years',
            field=models.CharField(blank=True, choices=[('0-5', '0-5 years'), ('6-15', '6-15 years'), ('16-25', '16-25 years'), ('25+', '25+ years')], max_length=10, null=True, verbose_name='Years of Teaching Experience'),
        ),
    ]
