# Generated by Django 6.0.1 on 2026-02-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_teacherprofile_age_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text="Leave blank to use 'First Last'. Use this for patronymics, middle names, or cultural naming conventions.", max_length=200, verbose_name='Display Name (Optional)'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', help_text='Your first/given name (required for certificate)', max_length=100, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Your family name/surname (required for certificate)', max_length=100, verbose_name='Last Name'),
        ),
    ]
