# Generated by Django 6.0.1 on 2026-02-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacherprofile_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='average_class_size',
            field=models.CharField(choices=[('small', 'Small (<15 students)'), ('medium', 'Medium (15-25 students)'), ('large', 'Large (26-35 students)'), ('very_large', 'Very Large (>35 students)')], max_length=20, null=True, verbose_name='Average Class Size'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text="Leave blank to use 'First Last'. Use this for patronymics, middle names, or cultural naming conventions (e.g., 'Ιωάννης Δούρβας του Γεωργίου')", max_length=200, verbose_name='Display Name (Optional)'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='grade_level',
            field=models.CharField(choices=[('kindergarten', 'Kindergarten / Pre-K'), ('primary', 'Primary / Elementary (1-6)'), ('lower_secondary', 'Lower Secondary / Middle School (7-9)'), ('upper_secondary', 'Upper Secondary / High School (10-12)'), ('university', 'University / Higher Education')], help_text='Which grade level do you primarily teach?', max_length=20, null=True, verbose_name='Grade Level'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='school_location',
            field=models.CharField(choices=[('urban', 'Urban Area'), ('suburban', 'Suburban Area'), ('rural', 'Rural / Remote Area')], max_length=20, null=True, verbose_name='School Location'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='teaching_years',
            field=models.CharField(choices=[('0-5', '0-5 years'), ('6-15', '6-15 years'), ('16-25', '16-25 years'), ('25+', '25+ years')], max_length=10, null=True, verbose_name='Years of Teaching Experience'),
        ),
    ]
