# Generated by Django 6.0.1 on 2026-02-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_teacherprofile_average_class_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('kindergarten', 'Kindergarten / Pre-K'), ('primary', 'Primary / Elementary (1-6)'), ('lower_secondary', 'Lower Secondary / Middle School (7-9)'), ('upper_secondary', 'Upper Secondary / High School (10-12)'), ('university', 'University / Higher Education')], help_text='Which grade level do you primarily teach?', max_length=20, null=True, verbose_name='Grade Level'),
        ),
    ]
