# Generated by Django 6.0.1 on 2026-05-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_teacherprofile_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='blog_subject_filter_preference',
            field=models.CharField(choices=[('my_subject', 'My subject only'), ('adjacent', 'Adjacent subjects'), ('all', 'All subjects')], default='adjacent', help_text="User's preferred Workshop feed filter mode (persisted across sessions).", max_length=20, verbose_name='Practice Workshop subject filter'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject_area',
            field=models.CharField(blank=True, choices=[('mathematics', 'Mathematics'), ('language_arts', 'Language Arts / English'), ('science', 'Science (General)'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('social_studies', 'Social Studies'), ('history', 'History'), ('geography', 'Geography'), ('foreign_languages', 'World Languages'), ('computer_science', 'Computer Science / ICT'), ('physical_education', 'Physical Education & Health'), ('arts', 'Arts'), ('special_education', 'Special Education'), ('early_childhood', 'Early Childhood Education'), ('other', 'Primary Teacher / General Education')], help_text='Your primary teaching subject', max_length=50, null=True, verbose_name='Subject Area'),
        ),
    ]
