# Generated by Django 6.0.1 on 2026-05-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_teacherprofile_blog_subject_filter_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='ai_disclosure_acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of acknowledgment of the EU AI Act Article 50 disclosure modal.', null=True, verbose_name='AI Disclosure Acknowledged At'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='current_curriculum_pressure',
            field=models.CharField(blank=True, choices=[('low', 'Low - flexible curriculum'), ('medium', 'Medium - standard pacing'), ('high', 'High - strict curriculum coverage demands'), ('variable', 'Variable - depends on term / class')], help_text='Workload context for personalised, workload-aware AI feedback.', max_length=20, null=True, verbose_name='Current Curriculum Pressure'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='institutional_ai_policy',
            field=models.CharField(blank=True, choices=[('none', 'No policy'), ('restrictive', 'Restrictive - AI use discouraged'), ('permissive', 'Permissive - AI use allowed'), ('explicit_supportive', 'Explicit and supportive - AI use encouraged'), ('unknown', 'I do not know')], help_text='School/institutional stance on AI use; informs M11/M12 contextual prompts.', max_length=30, null=True, verbose_name='Institutional AI Policy'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='student_population_special_needs',
            field=models.JSONField(blank=True, default=list, help_text="Multi-select. Allowed values: learning_disability, behavioural_support, physical_disability, language_minority, gifted, socioeconomic_disadvantage, none. 'none' is exclusive (cannot be combined with other values).", verbose_name='Student Population Special Needs'),
        ),
    ]
