# Generated by Django 6.0.1 on 2026-05-09 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_teacherprofile_ai_disclosure_acknowledged_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Snake-case name of the TeacherProfile field that changed.', max_length=50, verbose_name='Field Name')),
                ('old_value', models.TextField(help_text="JSON-serialized previous value. The literal string 'null' indicates Python None.", verbose_name='Old Value (JSON)')),
                ('new_value', models.TextField(help_text="JSON-serialized new value. The literal string 'null' indicates Python None.", verbose_name='New Value (JSON)')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('change_event_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID grouping all field changes from a single save() event.', verbose_name='Change Event UUID')),
                ('change_source', models.CharField(blank=True, default='', help_text="Optional. Set by the call site (view/script/admin) to identify what triggered the change. Examples: 'profile_edit', 'admin_action', 'phaseC_reset', 'data_migration'.", max_length=50, verbose_name='Change Source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Teacher Profile Change',
                'verbose_name_plural': 'Teacher Profile Changes',
                'db_table': 'teacher_profile_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['user', '-changed_at'], name='idx_profile_history_user_time'), models.Index(fields=['field_name'], name='idx_profile_history_field')],
            },
        ),
    ]
