# Generated by Django 6.0.1 on 2026-05-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_drop_not_null_subject_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='research_data_opted_out',
            field=models.BooleanField(default=False, help_text="Set to True when the user revokes research_participation consent OR triggers an account erasure (Phase C C.4). Future research analyses and exports MUST filter out users with this flag set. The user's already-collected data remains in the DB (no retroactive delete) but is excluded from new analyses per the user's withdrawal. Narrower data_sharing revocation does NOT toggle this flag.", verbose_name='Opted out of research data inclusion'),
        ),
    ]
