# Generated by Django 6.0.1 on 2026-05-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AilstItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(help_text="Monotonic 1-36 within (language, instrument_version). Drives UI ordering and 'Question N of 36' progress.")),
                ('paper_code', models.CharField(help_text="Paper's semantic label (P1, K10, A3, E7 etc.). Used as key in AilstResponse.responses JSONB. Joins items to responses.", max_length=10)),
                ('factor', models.CharField(choices=[('perception', 'AI Perception'), ('knowledge_skills', 'AI Knowledge and Skills'), ('applications_innovation', 'AI Applications and Innovation'), ('ethics', 'AI Ethics')], max_length=30)),
                ('language', models.CharField(choices=[('en', 'English'), ('el', 'Greek')], max_length=5)),
                ('item_text', models.TextField(help_text='The Likert prompt the teacher reads. Must NOT be edited post-deployment (validated instrument; altering invalidates measurement). For corrections or translations, mint a new instrument_version instead.')),
                ('is_reverse_scored', models.BooleanField(default=False, help_text='If True, scoring computes 6 - raw response. Per Ning et al. 2025, exactly K1, A3, E3 are reverse-scored (negation-framed items).')),
                ('instrument_version', models.CharField(default='ning_2025_v1', help_text="Versioning anchor. Future cultural/IRB adaptations get new version strings (e.g., 'ning_2025_v1_ihu_adapted'). Existing responses keep their version, preserving comparability. Current platform default is set in settings.AILST_CURRENT_VERSION.", max_length=20)),
            ],
            options={
                'verbose_name': 'AILST Item',
                'verbose_name_plural': 'AILST Items',
                'db_table': 'ailst_items',
                'ordering': ['language', 'instrument_version', 'item_number'],
                'indexes': [models.Index(fields=['language', 'instrument_version', 'factor', 'item_number'], name='idx_ailst_items_lookup'), models.Index(fields=['paper_code'], name='idx_ailst_items_papercode')],
                'unique_together': {('item_number', 'language', 'instrument_version'), ('paper_code', 'language', 'instrument_version')},
            },
        ),
    ]
