# Generated by Django 6.0.1 on 2026-05-10 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ailst', '0002_seed_ailst_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AilstResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint', models.CharField(choices=[('T0', 'T0 - post-onboarding baseline'), ('T1', 'T1 - post-M5'), ('T2', 'T2 - post-M15')], max_length=3)),
                ('language', models.CharField(default='en', help_text='Mirrors AilstItem.language for the items shown to this user.', max_length=5)),
                ('instrument_version', models.CharField(default='ning_2025_v1', help_text='Pinned at row creation; immutable thereafter. View layer reads settings.AILST_CURRENT_VERSION at first save.', max_length=20)),
                ('responses', models.JSONField(blank=True, default=dict, help_text='{"P1": 4, "K10": 2, ..., "E10": 3} with raw 1-5 values. Anchor mapping: 5=Fully applicable, 1=Completely not applicable. Reverse-scoring (K1, A3, E3) applied at compute time, not at storage.')),
                ('perception_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('knowledge_skills_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('applications_innovation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ethics_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_saved_at', models.DateTimeField(auto_now=True, help_text='Touched on every page save during partial fill. Useful for abandonment analytics: completed_at=NULL AND last_saved_at < NOW - 7d implies abandoned.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ailst_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AILST Response',
                'verbose_name_plural': 'AILST Responses',
                'db_table': 'ailst_responses',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['timepoint', 'completed_at'], name='idx_ailst_resp_timepoint_done')],
                'constraints': [models.CheckConstraint(condition=models.Q(('timepoint__in', ['T0', 'T1', 'T2'])), name='valid_timepoint')],
                'unique_together': {('user', 'timepoint')},
            },
        ),
    ]
