# Generated by Django 6.0.1 on 2026-05-11 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EpilogueCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Set when the user first lands on /epilogue/.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Set when the user clicks "Mark complete and continue" on the placeholder page (or, in the future spec, when Stage 3 is finished and the Learning Portrait is generated).', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='epilogue_completion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PROODOS Epilogue completion',
                'verbose_name_plural': 'PROODOS Epilogue completions',
                'db_table': 'epilogue_completions',
                'ordering': ['-started_at'],
            },
        ),
    ]
