# Generated by Django 6.0.1 on 2026-05-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epilogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epiloguecompletion',
            name='dialogue_entered',
            field=models.BooleanField(default=False, help_text='True once the user enters the Stage 1-3 dialogue; False means they chose to skip it. Q5 measured variable.'),
        ),
        migrations.AddField(
            model_name='epiloguecompletion',
            name='dialogue_turns',
            field=models.JSONField(blank=True, default=list, help_text='Conversation log: [{stage, role, content, model, generated_at}], plus any stage-skip records.'),
        ),
        migrations.AddField(
            model_name='epiloguecompletion',
            name='learning_portrait_generated_at',
            field=models.DateTimeField(blank=True, help_text='Set when the user accepts the Learning Portrait.', null=True),
        ),
        migrations.AddField(
            model_name='epiloguecompletion',
            name='learning_portrait_pdf',
            field=models.FileField(blank=True, help_text='Generated Learning Portrait PDF.', null=True, upload_to='epilogue_portraits/'),
        ),
        migrations.AddField(
            model_name='epiloguecompletion',
            name='learning_portrait_text',
            field=models.TextField(blank=True, default='', help_text='The accepted Learning Portrait narrative (300-400 words).'),
        ),
        migrations.AddField(
            model_name='epiloguecompletion',
            name='stage0_seen_at',
            field=models.DateTimeField(blank=True, help_text='Set when the user first views the Stage 0 dashboard.', null=True),
        ),
        migrations.AddField(
            model_name='epiloguecompletion',
            name='stage0_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Frozen Stage 0 semantic payload (DTP theme-evolution, RTM tension trajectories, quantitative summary). Computed once on first entry and rendered live from this JSON; never HTML.'),
        ),
        migrations.AddField(
            model_name='epiloguecompletion',
            name='stage1_completed_at',
            field=models.DateTimeField(blank=True, help_text='Set when Stage 1 (Look Back) finishes.', null=True),
        ),
        migrations.AddField(
            model_name='epiloguecompletion',
            name='stage2_completed_at',
            field=models.DateTimeField(blank=True, help_text='Set when Stage 2 (Look In) finishes or is skipped.', null=True),
        ),
        migrations.AddField(
            model_name='epiloguecompletion',
            name='stage3_completed_at',
            field=models.DateTimeField(blank=True, help_text='Set when Stage 3 (Look Forward) finishes.', null=True),
        ),
        migrations.AlterField(
            model_name='epiloguecompletion',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Set when the user finishes the Epilogue — after Stage 3 and Learning Portrait acceptance, or when they skip the dialogue. NULL means started but not yet finished.', null=True),
        ),
    ]
