# Generated by Django 6.0.1 on 2026-03-01 09:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0006_usermoduleprogress_reflection_peer_synthesis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Auto-generated from module title, e.g. "Συζήτηση: Κατανόηση AI στην Εκπαίδευση"', max_length=200, verbose_name='Thread Title')),
                ('seeded_question', models.TextField(blank=True, help_text='The discussion prompt set by the researcher to kickstart community engagement.', verbose_name='Seeded Question')),
                ('seeded_question_2', models.TextField(blank=True, help_text='Optional second prompt for deeper discussion.', verbose_name='Secondary Seeded Question')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked threads prevent new posts (use for completed cohorts)', verbose_name='Locked')),
                ('post_count', models.PositiveIntegerField(default=0, verbose_name='Post Count')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Activity')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_thread', to='modules.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Forum Thread',
                'verbose_name_plural': 'Forum Threads',
                'ordering': ['module__order_index'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_pseudonym', models.CharField(help_text='Snapshot of pseudonym at time of posting (GDPR-safe display name)', max_length=100, verbose_name='Author Pseudonym')),
                ('author_subject', models.CharField(blank=True, help_text='Snapshot of subject_area at time of posting', max_length=50, verbose_name='Author Subject Area')),
                ('author_grade', models.CharField(blank=True, help_text='Snapshot of grade_level at time of posting', max_length=50, verbose_name='Author Grade Level')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_seeded', models.BooleanField(default=False, help_text='Researcher-planted post to kickstart discussion. Shown with special styling.', verbose_name='Seeded by Researcher')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned posts appear at the top of the thread', verbose_name='Pinned')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete - content hidden but record preserved for research integrity', verbose_name='Deleted')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Helpful Votes')),
                ('source_tab', models.CharField(blank=True, choices=[('introduction', 'Tab 1 - Introduction'), ('main_content', 'Tab 2 - Main Content'), ('activity', 'Tab 3 - Activity'), ('assessment', 'Tab 4 - Assessment'), ('reflection', 'Tab 5 - Reflection'), ('community_page', 'Community Page')], help_text='Which tab the user clicked "Post to Forum" from', max_length=20, verbose_name='Source Tab')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('parent_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.forumpost', verbose_name='Parent Post')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.forumthread', verbose_name='Thread')),
            ],
            options={
                'verbose_name': 'Forum Post',
                'verbose_name_plural': 'Forum Posts',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumHelpfulVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_votes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='community.forumpost', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Helpful Vote',
                'verbose_name_plural': 'Helpful Votes',
                'indexes': [models.Index(fields=['post'], name='community_f_post_id_ec35a4_idx'), models.Index(fields=['user'], name='community_f_user_id_e81ee2_idx')],
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['thread', '-created_at'], name='community_f_thread__537dce_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['author'], name='community_f_author__db9996_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['parent_post'], name='community_f_parent__951d50_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['is_seeded'], name='community_f_is_seed_de39a5_idx'),
        ),
    ]
