# Generated by Django 6.0.1 on 2026-03-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='title',
            field=models.CharField(help_text='Auto-generated from module title, e.g. "Discussion: Understanding AI in Education"', max_length=200, verbose_name='Thread Title'),
        ),
    ]
