# Generated by Django 6.0.1 on 2026-03-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_forumthread_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='trigger_example',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='trigger_hint',
            field=models.TextField(default='Share your thoughts with your colleagues.'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='trigger_title',
            field=models.CharField(default='Join the discussion!', max_length=200),
        ),
    ]
